import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { useState } from "react";

const Home: NextPage = () => {
    const [newTodoText, setNewTodoText] = useState('');

    const todos = api.example.getAllTodos.useQuery(undefined, { refetchInterval: 1000 });

    const createNewTodoMutation = api.example.createNewTodo.useMutation();

    const sendTodo = () => {
        console.log('want to send todo to server', newTodoText);

        createNewTodoMutation.mutate({
            newText: newTodoText,
        });
    };

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex flex-col items-center mt-2">
                <div className="flex flex-row gap-2">
                    <input type="text" value={newTodoText}
                        onChange={(e) => setNewTodoText(e.target.value)}
                        className="bg-slate-300 border border-slate-400 rounded p-1"
                    />
                    <button onClick={() => sendTodo()} className="bg-slate-300 border border-black p-2 rounded">SEND</button>
                </div>
                {todos.data && todos.data.map(todo => (
                    <div key={todo.id}>
                        {todo.task}
                    </div>
                ))}
            </main>
        </>
    );
};

export default Home;
